spring:
  application:
    name: ScoreTracker
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:stdb'
    username: sa
    password:
    hikari:
      connection-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8080
