spring:
  application:
    name: anchoreer-chat
  data:
    redis:
      time-to-live: 300 # 데이터 유지 시간(sec) 1시간
      host: localhost
      port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 10
    producer:
      bootstrap-servers: localhost:9093
    backoff:
      interval: 1000
      max_failure: 3
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:acdb'
    username: sa
    password:
    hikari:
      connection-timeout: 300000
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
        show_sql: true
        format_sql: true
        use_sql_comments: true
server:
  port: 8080
