spring:
  application:
    name: anchoreer-chat
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:acdb'
    username: sa
    password:
    hikari:
      connection-timeout: 300000
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
        show_sql: true
        format_sql: true
        use_sql_comments: true

server:
  port: 8080
