name: Spring CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check working directory
        run: cd src/main/resources && pwd

      - name: Build and run Docker Compose
        run: |
          cd src/main/resources/docker
          docker-compose -f docker-compose.yml up -d
          docker image prune -f

      - name: Build with Gradle
        run: ./gradlew clean build --parallel

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: project-artifacts
          path: |
            drrr-api/build/libs/*.jar

    
